// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TunBasedBattler.Models;

namespace TunBasedBattler.Migrations
{
    [DbContext(typeof(tunbasedbattlerContext))]
    partial class tunbasedbattlerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TunBasedBattler.Models.Heroes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<int>("Attack")
                        .HasColumnName("attack")
                        .HasColumnType("int(11)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnName("class")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int>("Defence")
                        .HasColumnName("defence")
                        .HasColumnType("int(11)");

                    b.Property<decimal>("Dodge")
                        .HasColumnName("dodge")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("Hp")
                        .HasColumnName("hp")
                        .HasColumnType("int(11)");

                    b.Property<int>("Magic")
                        .HasColumnName("magic")
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("PlayerId")
                        .HasColumnName("player_id")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("name");

                    b.HasIndex("PlayerId")
                        .HasName("fk_heroes_players");

                    b.ToTable("heroes");
                });

            modelBuilder.Entity("TunBasedBattler.Models.Players", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnName("username")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasName("username");

                    b.ToTable("players");
                });

            modelBuilder.Entity("TunBasedBattler.Models.Heroes", b =>
                {
                    b.HasOne("TunBasedBattler.Models.Players", "Player")
                        .WithMany("Heroes")
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("fk_heroes_players")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
